INSERT INTO `pais` (`pai_id`, `pai_nombre`, `pai_capital`, `pai_iso2`, `pai_iso3`, `pai_codigo_fono`, `pai_descripcion`, `pai_nacionalidad`, `pai_estado`,  `pai_estado_logico`) VALUES
(72, 'Gabón', NULL, 'GA', 'GAB', '241', 'Gabón', NULL, '1', '1'),
(73, 'Gambia', NULL, 'GM', 'GMB', '220', 'Gambia', NULL, '1', '1'),
(74, 'Gales', NULL, 'GA', 'GAL', '44', 'Gales', NULL, '1', '1'),
(75, 'Georgia', NULL, 'GE', 'GEO', '995', 'Georgia', NULL, '1', '1'),
(76, 'Ghana', NULL, 'GH', 'GHA', '233', 'Ghana', NULL, '1', '1'),
(77, 'Gibraltar', NULL, 'GI', 'GIB', '350', 'Gibraltar', NULL, '1', '1'),
(78, 'Granada', NULL, 'GD', 'GRD', '1 473', 'Granada', NULL, '1', '1'),
(79, 'Grecia', NULL, 'GR', 'GRC', '30', 'Grecia', NULL, '1', '1'),
(80, 'Groenlandia', NULL, 'GL', 'GRL', '299', 'Groenlandia', NULL, '1', '1'),
(81, 'Guadalupe', NULL, 'GP', 'GLP', '', 'Guadalupe', NULL, '1', '1'),
(82, 'Guam', NULL, 'GU', 'GUM', '1 671', 'Guam', NULL, '1', '1'),
(83, 'Guatemala', NULL, 'GT', 'GTM', '502', 'Guatemala', NULL, '1', '1'),
(84, 'Guayana Francesa', NULL, 'GF', 'GUF', '', 'Guayana Francesa', NULL, '1', '1'),
(85, 'Guinea', NULL, 'GN', 'GIN', '224', 'Guinea', NULL, '1', '1'),
(86, 'Guinea Ecuatorial', NULL, 'GQ', 'GNQ', '240', 'Guinea Ecuatorial', NULL, '1', '1'),
(87, 'Guinea-Bissau', NULL, 'GW', 'GNB', '245', 'Guinea-Bissau', NULL, '1', '1'),
(88, 'Guyana', NULL, 'GY', 'GUY', '592', 'Guyana', NULL, '1', '1'),
(89, 'Haití', NULL, 'HT', 'HTI', '509', 'Haití', NULL, '1', '1'),
(90, 'Honduras', NULL, 'HN', 'HND', '504', 'Honduras', NULL, '1', '1'),
(91, 'Hungría', NULL, 'HU', 'HUN', '36', 'Hungría', NULL, '1', '1'),
(92, 'India', NULL, 'IN', 'IND', '91', 'India', NULL, '1', '1'),
(93, 'Inglaterra', NULL, 'IN', 'ING', '44', 'Inglaterra', NULL, '1', '1'),
(94, 'Irán', NULL, 'IR', 'IRN', '98', 'Irán', NULL, '1', '1'),
(95, 'Indonesia', NULL, 'ID', 'IDN', '62', 'Indonesia', NULL, '1', '1'),
(96, 'Irak', NULL, 'IQ', 'IRQ', '964', 'Irak', NULL, '1', '1'),
(97, 'Irlanda', NULL, 'IE', 'IRL', '353', 'Irlanda', NULL, '1', '1'),
(98, 'Islandia', NULL, 'IS', 'ISL', '354', 'Islandia', NULL, '1', '1'),
(99, 'Isla de Man', NULL, 'IM', 'IMN', '44', 'Isla de Man', NULL, '1', '1'),
(100, 'Islas Bermudas', NULL, 'BM', 'BMU', '1 441', 'Islas Bermudas', NULL, '1', '1'),
(101, 'Islas Caimán', NULL, 'KY', 'CYM', '1 345', 'Islas Caimán', NULL, '1', '1'),
(102, 'Islas Cocos (Keeling)', NULL, 'CC', 'CCK', '61', 'Islas Cocos (Keeling)', NULL, '1', '1'),
(103, 'Islas de Aland', NULL, 'AX', 'ALA', '', 'Islas de Åland', NULL, '1', '1'),
(104, 'Islas Feroe', NULL, 'FO', 'FRO', '298', 'Islas Feroe', NULL, '1', '1'),
(105, 'Islas Georgias del Sur y Sandwich del Sur', NULL, 'GS', 'SGS', '', 'Islas Georgias del Sur y Sandwich del Sur', NULL, '1', '1'),
(106, 'Islas Maldivas', NULL, 'MV', 'MDV', '960', 'Islas Maldivas', NULL, '1', '1'),
(107, 'Islas Malvinas', NULL, 'FK', 'FLK', '500', 'Islas Malvinas', NULL, '1', '1'),
(108, 'Islas Marianas del Norte', NULL, 'MP', 'MNP', '1 670', 'Islas Marianas del Norte', NULL, '1', '1'),
(109, 'Cantón de Islas Marshall', NULL, 'MH', 'MHL', '692', 'Cantón de Islas Marshall', NULL, '1', '1'),
(110, 'Islas Pitcairn', NULL, 'PN', 'PCN', '870', 'Islas Pitcairn', NULL, '1', '1'),
(111, 'Islas Salomón', NULL, 'SB', 'SLB', '677', 'Islas Salomón', NULL, '1', '1'),
(112, 'Islas Turcas y Caicos', NULL, 'TC', 'TCA', '1 649', 'Islas Turcas y Caicos', NULL, '1', '1'),
(113, 'Islas Ultramarinas Menores de Estados Unidos', NULL, 'UM', 'UMI', '', 'Islas Ultramarinas Menores de Estados Unidos', NULL, '1', '1'),
(114, 'Islas Vírgenes Británicas', NULL, 'VG', 'VG', '1 284', 'Islas Vírgenes Británicas', NULL, '1', '1'),
(115, 'Islas Vírgenes de los Estados Unidos', NULL, 'VI', 'VIR', '1 340', 'Islas Vírgenes de los Estados Unidos', NULL, '1', '1'),
(116, 'Israel', NULL, 'IL', 'ISR', '972', 'Israel', NULL, '1', '1'),
(117, 'Italia', NULL, 'IT', 'ITA', '39', 'Italia', NULL, '1', '1'),
(118, 'Jamaica', NULL, 'JM', 'JAM', '1 876', 'Jamaica', NULL, '1', '1'),
(119, 'Japón', NULL, 'JP', 'JPN', '81', 'Japón', NULL, '1', '1'),
(120, 'Jersey', NULL, 'JE', 'JEY', '', 'Jersey', NULL, '1', '1'),
(121, 'Jordania', NULL, 'JO', 'JOR', '962', 'Jordania', NULL, '1', '1'),
(122, 'Kazajistán', NULL, 'KZ', 'KAZ', '7', 'Kazajistán', NULL, '1', '1'),
(123, 'Kenia', NULL, 'KE', 'KEN', '254', 'Kenia', NULL, '1', '1'),
(124, 'Kirgizstán', NULL, 'KG', 'KGZ', '996', 'Kirgizstán', NULL, '1', '1'),
(125, 'Kiribati', NULL, 'KI', 'KIR', '686', 'Kiribati', NULL, '1', '1'),
(126, 'Kuwait', NULL, 'KW', 'KWT', '965', 'Kuwait', NULL, '1', '1'),
(127, 'Líbano', NULL, 'LB', 'LBN', '961', 'Líbano', NULL, '1', '1'),
(128, 'Laos', NULL, 'LA', 'LAO', '856', 'Laos', NULL, '1', '1'),
(129, 'Lesoto', NULL, 'LS', 'LSO', '266', 'Lesoto', NULL, '1', '1'),
(130, 'Letonia', NULL, 'LV', 'LVA', '371', 'Letonia', NULL, '1', '1'),
(131, 'Liberia', NULL, 'LR', 'LBR', '231', 'Liberia', NULL, '1', '1'),
(132, 'Libia', NULL, 'LY', 'LBY', '218', 'Libia', NULL, '1', '1'),
(133, 'Liechtenstein', NULL, 'LI', 'LIE', '423', 'Liechtenstein', NULL, '1', '1'),
(134, 'Lituania', NULL, 'LT', 'LTU', '370', 'Lituania', NULL, '1', '1'),
(135, 'Luxemburgo', NULL, 'LU', 'LUX', '352', 'Luxemburgo', NULL, '1', '1'),
(136, 'México', NULL, 'MX', 'MEX', '52', 'México', NULL, '1', '1'),
(137, 'Mónaco', NULL, 'MC', 'MCO', '377', 'Mónaco', NULL, '1', '1'),
(138, 'Macao', NULL, 'MO', 'MAC', '853', 'Macao', NULL, '1', '1'),
(139, 'Macedonia', NULL, 'MK', 'MKD', '389', 'Macedonia', NULL, '1', '1'),
(140, 'Madagascar', NULL, 'MG', 'MDG', '261', 'Madagascar', NULL, '1', '1'),
(141, 'Malasia', NULL, 'MY', 'MYS', '60', 'Malasia', NULL, '1', '1'),
(142, 'Malawi', NULL, 'MW', 'MWI', '265', 'Malawi', NULL, '1', '1'),
(143, 'Mali', NULL, 'ML', 'MLI', '223', 'Mali', NULL, '1', '1'),
(144, 'Malta', NULL, 'MT', 'MLT', '356', 'Malta', NULL, '1', '1'),
(145, 'Marruecos', NULL, 'MA', 'MAR', '212', 'Marruecos', NULL, '1', '1'),
(146, 'Martinica', NULL, 'MQ', 'MTQ', '', 'Martinica', NULL, '1', '1'),
(147, 'Mauricio', NULL, 'MU', 'MUS', '230', 'Mauricio', NULL, '1', '1'),
(148, 'Mauritania', NULL, 'MR', 'MRT', '222', 'Mauritania', NULL, '1', '1'),
(149, 'Micronesia', NULL, 'FM', 'FSM', '691', 'Micronesia', NULL, '1', '1'),
(150, 'Moldavia', NULL, 'MD', 'MDA', '373', 'Moldavia', NULL, '1', '1'),
(151, 'Mongolia', NULL, 'MN', 'MNG', '976', 'Mongolia', NULL, '1', '1'),
(152, 'Montenegro', NULL, 'ME', 'MNE', '382', 'Montenegro', NULL, '1', '1'),
(153, 'Montserrat', NULL, 'MS', 'MSR', '1 664', 'Montserrat', NULL, '1', '1'),
(154, 'Mozambique', NULL, 'MZ', 'MOZ', '258', 'Mozambique', NULL, '1', '1'),
(155, 'Namibia', NULL, 'NA', 'NAM', '264', 'Namibia', NULL, '1', '1'),
(156, 'Nauru', NULL, 'NR', 'NRU', '674', 'Nauru', NULL, '1', '1'),
(157, 'Nepal', NULL, 'NP', 'NPL', '977', 'Nepal', NULL, '1', '1'),
(158, 'Nicaragua', NULL, 'NI', 'NIC', '505', 'Nicaragua', NULL, '1', '1'),
(159, 'Nigeria', NULL, 'NG', 'NGA', '234', 'Nigeria', NULL, '1', '1'),
(160, 'Niue', NULL, 'NU', 'NIU', '683', 'Niue', NULL, '1', '1'),
(161, 'Noruega', NULL, 'NO', 'NOR', '47', 'Noruega', NULL, '1', '1'),
(162, 'Nueva Caledonia', NULL, 'NC', 'NCL', '687', 'Nueva Caledonia', NULL, '1', '1'),
(163, 'Nueva Zelanda', NULL, 'NZ', 'NZL', '64', 'Nueva Zelanda', NULL, '1', '1'),
(164, 'Omán', NULL, 'OM', 'OMN', '968', 'Omán', NULL, '1', '1'),
(165, 'Países Bajos', NULL, 'NL', 'NLD', '31', 'Países Bajos', NULL, '1', '1'),
(166, 'Pakistán', NULL, 'PK', 'PAK', '92', 'Pakistán', NULL, '1', '1'),
(167, 'Palau', NULL, 'PW', 'PLW', '680', 'Palau', NULL, '1', '1'),
(168, 'Palestina', NULL, 'PS', 'PSE', '', 'Palestina', NULL, '1', '1'),
(169, 'Panamá', NULL, 'PA', 'PAN', '507', 'Panamá', NULL, '1', '1'),
(170, 'Papúa Nueva Guinea', NULL, 'PG', 'PNG', '675', 'Papúa Nueva Guinea', NULL, '1', '1'),
(171, 'Paraguay', NULL, 'PY', 'PRY', '595', 'Paraguay', NULL, '1', '1'),
(172, 'Perú', NULL, 'PE', 'PER', '51', 'Perú', NULL, '1', '1'),
(173, 'Polinesia Francesa', NULL, 'PF', 'PYF', '689', 'Polinesia Francesa', NULL, '1', '1'),
(174, 'Polonia', NULL, 'PL', 'POL', '48', 'Polonia', NULL, '1', '1'),
(175, 'Portugal', NULL, 'PT', 'PRT', '351', 'Portugal', NULL, '1', '1'),
(176, 'Puerto Rico', NULL, 'PR', 'PRI', '1', 'Puerto Rico', NULL, '1', '1'),
(177, 'Qatar', NULL, 'QA', 'QAT', '974', 'Qatar', NULL, '1', '1'),
(178, 'Reino Unido', NULL, 'GB', 'GBR', '44', 'Reino Unido', NULL, '1', '1'),
(179, 'República Centroafricana', NULL, 'CF', 'CAF', '236', 'República Centroafricana', NULL, '1', '1'),
(180, 'República Checa', NULL, 'CZ', 'CZE', '420', 'República Checa', NULL, '1', '1'),
(181, 'República Dominicana', NULL, 'DO', 'DOM', '1 809', 'República Dominicana', NULL, '1', '1'),
(182, 'Ruanda', NULL, 'RW', 'RWA', '250', 'Ruanda', NULL, '1', '1'),
(183, 'Rumanía', NULL, 'RO', 'ROU', '40', 'Rumanía', NULL, '1', '1'),
(184, 'Rusia', NULL, 'RU', 'RUS', '7', 'Rusia', NULL, '1', '1'),
(185, 'Sahara Occidental', NULL, 'EH', 'ESH', '', 'Sahara Occidental', NULL, '1', '1'),
(186, 'Samoa', NULL, 'WS', 'WSM', '685', 'Samoa', NULL, '1', '1'),
(187, 'Samoa Americana', NULL, 'AS', 'ASM', '1 684', 'Samoa Americana', NULL, '1', '1'),
(188, 'San Cristóbal y Nieves', NULL, 'KN', 'KNA', '1 869', 'San Cristóbal y Nieves', NULL, '1', '1'),
(189, 'San Marino', NULL, 'SM', 'SMR', '378', 'San Marino', NULL, '1', '1'),
(190, 'San Vicente y las Granadinas', NULL, 'VC', 'VCT', '1 784', 'San Vicente y las Granadinas', NULL, '1', '1'),
(191, 'Santa Lucía', NULL, 'LC', 'LCA', '1 758', 'Santa Lucía', NULL, '1', '1'),
(192, 'Santo Tomé y Príncipe', NULL, 'ST', 'STP', '239', 'Santo Tomé y Príncipe', NULL, '1', '1'),
(193, 'Senegal', NULL, 'SN', 'SEN', '221', 'Senegal', NULL, '1', '1'),
(194, 'Serbia', NULL, 'RS', 'SRB', '381', 'Serbia', NULL, '1', '1'),
(195, 'Seychelles', NULL, 'SC', 'SYC', '248', 'Seychelles', NULL, '1', '1'),
(196, 'Sierra Leona', NULL, 'SL', 'SLE', '232', 'Sierra Leona', NULL, '1', '1'),
(197, 'Singapur', NULL, 'SG', 'SGP', '65', 'Singapur', NULL, '1', '1'),
(198, 'Siria', NULL, 'SY', 'SYR', '963', 'Siria', NULL, '1', '1'),
(199, 'Somalia', NULL, 'SO', 'SOM', '252', 'Somalia', NULL, '1', '1'),
(200, 'Sri lanka', NULL, 'LK', 'LKA', '94', 'Sri lanka', NULL, '1', '1'),
(201, 'Sudáfrica', NULL, 'ZA', 'ZAF', '27', 'Sudáfrica', NULL, '1', '1'),
(202, 'Sudán', NULL, 'SD', 'SDN', '249', 'Sudán', NULL, '1', '1'),
(203, 'Suecia', NULL, 'SE', 'SWE', '46', 'Suecia', NULL, '1', '1'),
(204, 'Suiza', NULL, 'CH', 'CHE', '41', 'Suiza', NULL, '1', '1'),
(205, 'Surinám', NULL, 'SR', 'SUR', '597', 'Surinám', NULL, '1', '1'),
(206, 'Svalbard y Jan Mayen', NULL, 'SJ', 'SJM', '', 'Svalbard y Jan Mayen', NULL, '1', '1'),
(207, 'Swazilandia', NULL, 'SZ', 'SWZ', '268', 'Swazilandia', NULL, '1', '1'),
(208, 'Tayikistán', NULL, 'TJ', 'TJK', '992', 'Tayikistán', NULL, '1', '1'),
(209, 'Tailandia', NULL, 'TH', 'THA', '66', 'Tailandia', NULL, '1', '1'),
(210, 'Tanzania', NULL, 'TZ', 'TZA', '255', 'Tanzania', NULL, '1', '1'),
(211, 'Territorios Australes y Antárticas Franceses', NULL, 'TF', 'ATF', '', 'Territorios Australes y Antárticas Franceses', NULL, '1', '1'),
(212, 'Timor Oriental', NULL, 'TL', 'TLS', '670', 'Timor Oriental', NULL, '1', '1'),
(213, 'Togo', NULL, 'TG', 'TGO', '228', 'Togo', NULL, '1', '1'),
(214, 'Tonga', NULL, 'TO', 'TON', '676', 'Tonga', NULL, '1', '1'),
(215, 'Trinidad y Tobago', NULL, 'TT', 'TTO', '1 868', 'Trinidad y Tobago', NULL, '1', '1'),
(216, 'Tunez', NULL, 'TN', 'TUN', '216', 'Tunez', NULL, '1', '1'),
(217, 'Turkmenistán', NULL, 'TM', 'TKM', '993', 'Turkmenistán', NULL, '1', '1'),
(218, 'Turquía', NULL, 'TR', 'TUR', '90', 'Turquía', NULL, '1', '1'),
(219, 'Tuvalu', NULL, 'TV', 'TUV', '688', 'Tuvalu', NULL, '1', '1'),
(220, 'Ucrania', NULL, 'UA', 'UKR', '380', 'Ucrania', NULL, '1', '1'),
(221, 'Uganda', NULL, 'UG', 'UGA', '256', 'Uganda', NULL, '1', '1'),
(222, 'Uruguay', NULL, 'UY', 'URY', '598', 'Uruguay', NULL, '1', '1'),
(223, 'Uzbekistán', NULL, 'UZ', 'UZB', '998', 'Uzbekistán', NULL, '1', '1'),
(224, 'Vanuatu', NULL, 'VU', 'VUT', '678', 'Vanuatu', NULL, '1', '1'),
(225, 'Venezuela', NULL, 'VE', 'VEN', '58', 'Venezuela', NULL, '1', '1'),
(226, 'Vietnam', NULL, 'VN', 'VNM', '84', 'Vietnam', NULL, '1', '1'),
(227, 'Yemen', NULL, 'YE', 'YEM', '967', 'Yemen', NULL, '1', '1'),
(228, 'Yibuti', NULL, 'DJ', 'DJI', '253', 'Yibuti', NULL, '1', '1'),
(229, 'Zambia', NULL, 'ZM', 'ZMB', '260', 'Zambia', NULL, '1', '1'),
(230, 'Zimbabue', NULL, 'ZW', 'ZWE', '263', 'Zimbabue', NULL, '1', '1');








